language: ruby
rvm:
  - "2.4.1"
env:
  - DB=postgres
before_script:
  - psql -c 'create database travis;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
