language: ruby
services:
  - postgresql
rvm:
  - "2.4.1"
env:
  - ENV=test
before_script:
  - psql -c 'create database rigotheceo_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
